### ISSUE TITLE
uchar.h is missing on macOS

### ISSUE THREAD

**Issue by mbrobbel** [eqrion/cbindgen#423]
We're using `cbindgen` to generate both C and C++ headers in our project. However, the generated C header fails to build on macOS with the 0.10.1 release (https://github.com/mbrobbel/dqcsim/pull/313) because `uchar.h` is missing on macOS.

```
target/include/dqcsim.h:5:10: fatal error: 'uchar.h' file not found
#include <uchar.h>
         ^~~~~~~~~
```

**Comment by emilio** [comment]
What header defines `char32_t`? Is it built-in?

**Comment by emilio** [comment]
(Sorry, I don't have a mac so I cannot test that myself)

**Comment by emilio** [comment]
cc @adrianwong. Maybe we should just switch to uint32_t for now?

**Comment by mbrobbel** [comment]
> What header defines `char32_t`? Is it built-in?

I think there is no header available, and it's not built-in unfortunately. Something like this should work I guess:

```c
#ifdef __APPLE__
#include <stdint.h>
typedef uint16_t char16_t;
typedef uint32_t char32_t;
#else
#include <uchar.h>
#endif
```

**Comment by laser** [comment]
This issue also impacted [our Darwin builds](https://circleci.com/gh/filecoin-project/filecoin-ffi/203) once we updated cbindgen from 0.10.0 to 0.10.1.

**Comment by emilio** [comment]
Ok, I put up https://github.com/eqrion/cbindgen/pull/424 for this. I decided to use `uint32_t` because I also think it's needed for correctness, see the comment in the code there.

**Comment by adrianwong** [comment]
@emilio Yeah, `uint32_t` seems like it'll be the most appropriate type to use. The build for #424 has some test failures, which I'm happy to try fixing as this is a bug I introduced.

**Comment by emilio** [comment]
The tests in that PR seem unrelated to the change, I think it's a rust nightly change / regression (they're the `cargo-expand` tests, which require nightly)

**Comment by emilio** [comment]
Ah no, I just forgot to run the tests locally as I had a stable compiler. Should be green now :)

**Comment by emilio** [comment]
(But thanks a lot for the offer @adrianwong!)

**Comment by adrianwong** [comment]
Thanks for fixing this @emilio! And apologies all for not testing the `char32_t` changes on macOS.

**Comment by emilio** [comment]
No worries, I can't test it on mac myself either, and the CI situation there is not amazing (though may be better now? We should investigate adding Mac to our CI if possible).

Thanks for being responsive (and to the reporters for the fast issue-filing :)).

**Comment by emilio** [comment]
Landed that and published v0.11.0, as it is technically a breaking change for C++ bindings unfortunately.
