### ISSUE TITLE
Cbindgen 0.29.4 causes Firefox not to build: use of undeclared identifier 'COUNT'

### ISSUE THREAD

**Issue by nteodosio** [eqrion/cbindgen#1165]
With Cbindgen 0.29.4, Firefox ESR, nightly, Thunderbird beta started failing to build on Ubuntu 24.04 on all architectures we build for (ARM and x64):
```
:: 11:10.89 In file included from /build/firefox/parts/firefox/build/accessible/atk/nsMaiInterfaceComponent.cpp:17:
:: 11:10.89 In file included from /build/firefox/parts/firefox/build/obj-x86_64-pc-linux-gnu/instrumented/dist/include/mozilla/dom/BrowserParent.h:25:
:: 11:10.89 In file included from /build/firefox/parts/firefox/build/obj-x86_64-pc-linux-gnu/instrumented/dist/include/mozilla/layout/RemoteLayerTreeOwner.h:17:
:: 11:10.89 In file included from /build/firefox/parts/firefox/build/obj-x86_64-pc-linux-gnu/instrumented/dist/include/nsDisplayList.h:23:
:: 11:10.89 In file included from /build/firefox/parts/firefox/build/obj-x86_64-pc-linux-gnu/instrumented/dist/include/gfxContext.h:11:
:: 11:10.89 In file included from /build/firefox/parts/firefox/build/obj-x86_64-pc-linux-gnu/instrumented/dist/include/gfxUtils.h:24:
:: 11:10.89 In file included from /build/firefox/parts/firefox/build/obj-x86_64-pc-linux-gnu/instrumented/dist/include/mozilla/webrender/WebRenderTypes.h:11:
:: 11:10.89 In file included from /build/firefox/parts/firefox/build/obj-x86_64-pc-linux-gnu/instrumented/dist/include/mozilla/webrender/webrender_ffi.h:103:
:: 11:10.89 /build/firefox/parts/firefox/build/obj-x86_64-pc-linux-gnu/instrumented/dist/include/mozilla/webrender/webrender_ffi_generated.h:6718:53: error: use of undeclared identifier 'COUNT'
:: 11:10.89 constexpr static const BudgetType BudgetType_VALUES[COUNT] = { BudgetType::SharedColor8Linear, BudgetType::SharedColor8Nearest, BudgetType::SharedColor8Glyphs, BudgetType::SharedAlpha8, BudgetType::SharedAlpha8Glyphs, BudgetType::SharedAlpha16, BudgetType::Standalone, };
:: 11:10.89                                                     ^
```
[(Full log of 140.12.0esr)](https://launchpadlibrarian.net/864504940/buildlog_snap_ubuntu_jammy_amd64_firefox-snap-esr_BUILDING.txt.gz)

With Cbindgen 0.29.2 the build is OK.

**Comment by emilio** [comment]
Yeah, see https://bugzilla.mozilla.org/show_bug.cgi?id=2046162. It's technically a pre-existing issue on how we do constants that got uncovered by us supporting arrays.

**Comment by ernibert** [comment]
There is no 0.29.4 release, just a tag.  0.29.2 is the latest release.

On what is to rely on, releases or tags? If tags which one, those with a 'v' or those just like x.y.z?

**Comment by emilio** [comment]
There was a release on crates.io (same for 0.29.3). It seems GitHub changed something and now I need to manually un-draft the release (sigh).

**Comment by nteodosio** [comment]
Yeah I can confirm that is what cargo install cbindgen pulls.

Moreover, Firefox nightly insists:

::  0:13.16 E ERROR: cbindgen version 0.29.2 is too old. At least version
0.29.4 is required.

**Comment by landryb** [comment]
the patch/commit from https://bugzilla.mozilla.org/show_bug.cgi?id=2046162 allows to build 140esr with cbindgen 0.29.4.
